event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /

user_routes:
    resource: "@UserBundle/Controller"
    type: annotation

event_reports:
    resource: "@EventBundle/Controller/ReportController.php"
    type: annotation
