event_event:
    resource: "@EventBundle/Resources/config/routing/event.yml"
    prefix:   /

event_homepage:
    path:     /{count}/{firstName}
    defaults: { _controller: EventBundle:Default:index }

