event_homepage:
    path:     /{firstName}
    defaults: { _controller: EventBundle:Default:index }

event_testpage:
    path: /json/{firstName}
    defaults: { _controller: EventBundle:Default:test }
